limit: 1000
memory_size: 40
input_streams:
  0x80: [-1]
  0x84: []
reports:
  - name: Step-by-step log
    slice: all
    view: |
      ACC: {Acc:dec}
      {pc}: {instruction} {pc:label}  
  - name: Result log
    slice: last
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [32]