name: assert hello_user_cstr('Alice\n') == ('What is your name?\nHello, Alice!', '')
# and mem[0..31]: 48 65 6c 6c 6f 2c 20 41 6c 69 63 65 21 00 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f
limit: 1000
memory_size: 0x1000
input_streams:
  0x80: [65, 108, 105, 99, 101, 10]
  0x84: []
reports:
  - name: Step-by-step
    slice: all
    view: |
      T A B {T:hex} {A:hex} {B:hex}
      {pc}:	{instruction}	{pc:label}
  - name: Check results
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
      symio[0x80]: {io:0x80:sym}
      symio[0x84]: {io:0x84:sym}
      {memory:0:31}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [87,104,97,116,32,105,115,32,121,111,117,114,32,110,97,109,101,63,10,72,101,108,108,111,44,32,65,108,105,99,101,33]
      symio[0x80]: "" >>> ""
      symio[0x84]: "" >>> "What is your name?\nHello, Alice!"
      mem[0..31]: 	48 65 6c 6c 6f 2c 20 41 6c 69 63 65 21 00 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f