name: assert sum_word_cstream([1, -1, 0]) == [0, 0]
limit: 2000
memory_size: 0x1000
input_streams:
  0x80: [1, -1, 0]
  0x84: []
reports:
  - name: step-by-step
    slice: all
    view: |
      {T0} {T1} {T2} {T3}
      {pc}:	{instruction}	{pc:label}
  - name: Check results
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [0,0]